// ─────────────────────────────────────────────────────────────────────────────
// Policy key catalogue — the SCHEMA of the Policy Registry.
//
// This file declares WHAT keys exist. The database holds WHAT they are currently
// set to. Same split as notifications/catalog.js, and for the same reason: the
// shape of the system is reviewable in a PR and deploys atomically with the code
// that consumes it, while the values stay operator-editable without a deploy.
//
// Three fields do the real work:
//
//   fallback           the value the code uses when the Registry is unseeded or
//                      unreachable. Seeded as v1, so adopting the Registry is a
//                      no-op replica of today's behaviour — NOT a silent mass
//                      application of the Terms & Conditions.
//
//   clause             the T&C clause that governs this key, or null when the key
//                      is purely operational and the contract says nothing.
//
//   clauseExpectation  what that clause states the value should be, when it states
//                      a number at all. `fallback !== clauseExpectation` IS the
//                      conflict — detected automatically, reported, and never
//                      auto-applied (see conflicts.js and docs/12).
//
// Values here are DATA. Nothing in this file is ever evaluated. The logic that
// uses a value stays in the module that owns it — refunds/policy.js still decides
// how a refund is banded; it just stops holding the numbers.
// ─────────────────────────────────────────────────────────────────────────────

/** Snapshot boundaries — when a scope's values freeze onto a transaction. */
export const SCOPES = {
  BOOKING: 'booking', // frozen at confirmation
  ASSIGNMENT: 'assignment', // frozen at partner acceptance
  CLAIM: 'claim', // frozen at claim submission
  TICKET: 'ticket', // frozen at ticket creation
  GLOBAL: 'global', // never frozen; always resolved live
};

export const TYPES = {
  INTEGER: 'integer',
  DECIMAL: 'decimal',
  PERCENT: 'percent', // 0–100
  RATE: 'rate', // 0–1
  MONEY: 'money', // MYR
  BOOLEAN: 'boolean',
  ENUM: 'enum',
  LIST: 'list',
  JSON: 'json',
};

export const OWNERS = {
  FINANCE: 'finance',
  OPS: 'ops',
  LEGAL: 'legal',
  TRUST: 'trust',
  ENGINEERING: 'engineering',
};

/**
 * One entry per business rule.
 *
 * `source` records where the value lives today, so the migration can be checked
 * off key by key and a conflict report can name a real file:line.
 */
export const POLICY_KEYS = [
  // ── Booking ────────────────────────────────────────────────────────────────
  {
    key: 'booking.slot_hold_minutes',
    domain: 'booking',
    type: TYPES.INTEGER,
    unit: 'minutes',
    bounds: { min: 1, max: 60 },
    scope: SCOPES.GLOBAL,
    audience: ['consumer'],
    fallback: null, // NOT IMPLEMENTED — conflict C-12
    clause: '6.3',
    clauseExpectation: 10,
    owner: OWNERS.OPS,
    description: 'How long a selected slot is reserved pending payment authorisation.',
    source: null,
  },
  {
    key: 'booking.dispatch_accept_minutes',
    domain: 'booking',
    type: TYPES.INTEGER,
    unit: 'minutes',
    bounds: { min: 1, max: 60 },
    scope: SCOPES.GLOBAL,
    audience: ['partner'],
    fallback: null, // NOT IMPLEMENTED — conflict C-12
    clause: '6.5',
    clauseExpectation: 10,
    owner: OWNERS.OPS,
    description: 'Window a partner has to accept a dispatched booking.',
    source: null,
  },
  {
    key: 'booking.arrival_grace_minutes',
    domain: 'booking',
    type: TYPES.INTEGER,
    unit: 'minutes',
    bounds: { min: 0, max: 120 },
    scope: SCOPES.BOOKING,
    audience: ['consumer', 'partner'],
    fallback: null, // NOT IMPLEMENTED — conflict C-12
    clause: '6.14',
    clauseExpectation: 15,
    owner: OWNERS.OPS,
    description: 'How long a partner waits on site before a customer no-show may be recorded.',
    source: null,
  },
  {
    key: 'booking.reschedule_free_hours',
    domain: 'booking',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 0, max: 168 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: null, // NOT IMPLEMENTED
    clause: '6.8',
    clauseExpectation: 4,
    owner: OWNERS.OPS,
    description: 'Notice above which rescheduling is free of charge.',
    source: null,
  },
  {
    key: 'booking.max_reschedules',
    domain: 'booking',
    type: TYPES.INTEGER,
    unit: 'count',
    bounds: { min: 1, max: 10 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: null,
    clause: '6.8',
    clauseExpectation: 2,
    owner: OWNERS.OPS,
    description: 'Reschedules of one booking beyond which it may be cancelled with a fee.',
    source: null,
  },
  {
    key: 'booking.working_hours',
    domain: 'booking',
    type: TYPES.JSON,
    unit: null,
    bounds: null,
    scope: SCOPES.GLOBAL,
    audience: ['consumer', 'partner'],
    fallback: { start: '08:00', end: '22:00', timezone: 'Asia/Kuala_Lumpur' },
    clause: '2.1',
    clauseExpectation: { start: '08:00', end: '22:00', timezone: 'Asia/Kuala_Lumpur' },
    owner: OWNERS.OPS,
    description: 'Standard window within which services are scheduled.',
    source: 'server/lib/bookingEngineConfig.js',
  },

  // ── Cancellation ───────────────────────────────────────────────────────────
  {
    key: 'cancellation.free_window_hours',
    domain: 'cancellation',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 0, max: 168 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    // Today the free window is expressed only as the 100% refund tier, which
    // sits at 48h. See refund.full_refund_hours — same conflict, two keys.
    fallback: 48,
    clause: '8.1',
    clauseExpectation: 4,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Notice above which a customer may cancel free of charge.',
    source: 'server/lib/refunds/policy.js:17',
  },
  {
    key: 'cancellation.fee_min_myr',
    domain: 'cancellation',
    type: TYPES.MONEY,
    unit: 'myr',
    bounds: { min: 0, max: 500 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: null, // NOT IMPLEMENTED — conflict C-02
    clause: '8.2',
    clauseExpectation: 15,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Lower bound of the standard late-cancellation fee band.',
    source: null,
  },
  {
    key: 'cancellation.fee_max_myr',
    domain: 'cancellation',
    type: TYPES.MONEY,
    unit: 'myr',
    bounds: { min: 0, max: 500 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: null, // NOT IMPLEMENTED — conflict C-02
    clause: '8.2',
    clauseExpectation: 30,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Upper bound of the standard late-cancellation fee band.',
    source: null,
  },
  {
    key: 'cancellation.high_value_threshold_myr',
    domain: 'cancellation',
    type: TYPES.MONEY,
    unit: 'myr',
    bounds: { min: 0, max: 10000 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: null, // NOT IMPLEMENTED — conflict C-02
    clause: '8.2',
    clauseExpectation: 300,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Booking value above which a percentage cancellation fee may apply.',
    source: null,
  },
  {
    key: 'cancellation.high_value_fee_percent',
    domain: 'cancellation',
    type: TYPES.PERCENT,
    unit: 'percent',
    bounds: { min: 0, max: 100 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: null, // NOT IMPLEMENTED — conflict C-02
    clause: '8.2',
    clauseExpectation: 50,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Maximum cancellation fee, as a percentage, on high-value bookings.',
    source: null,
  },
  {
    key: 'cancellation.repeat_limit',
    domain: 'cancellation',
    type: TYPES.INTEGER,
    unit: 'count',
    bounds: { min: 1, max: 20 },
    scope: SCOPES.GLOBAL,
    audience: ['consumer'],
    fallback: null,
    clause: '8.4',
    clauseExpectation: 3,
    owner: OWNERS.TRUST,
    description: 'Late cancellations or no-shows in the rolling window before restrictions apply.',
    source: null,
  },
  {
    key: 'cancellation.repeat_window_days',
    domain: 'cancellation',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 1, max: 365 },
    scope: SCOPES.GLOBAL,
    audience: ['consumer'],
    fallback: null,
    clause: '8.4',
    clauseExpectation: 30,
    owner: OWNERS.TRUST,
    description: 'Rolling window over which repeat cancellations are counted.',
    source: null,
  },

  // ── Refund ─────────────────────────────────────────────────────────────────
  {
    key: 'refund.full_refund_hours',
    domain: 'refund',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 0, max: 720 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: 48,
    clause: '8.1',
    clauseExpectation: 4,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Notice above which a cancellation is refunded in full.',
    source: 'server/lib/refunds/policy.js:17',
  },
  {
    key: 'refund.partial_refund_hours',
    domain: 'refund',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 0, max: 720 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: 4,
    clause: '8.2',
    clauseExpectation: 4,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Notice below which the lowest refund tier applies.',
    source: 'server/lib/refunds/policy.js:18',
  },
  {
    key: 'refund.mid_tier_percent',
    domain: 'refund',
    type: TYPES.PERCENT,
    unit: 'percent',
    bounds: { min: 0, max: 100 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: 75,
    clause: '8.1',
    // 8.1 gives a FULL refund above the free window, so any partial tier that
    // begins above it contradicts the clause.
    clauseExpectation: 100,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Refund percentage between the partial and full notice thresholds.',
    source: 'server/lib/refunds/policy.js:99',
  },
  {
    key: 'refund.low_tier_percent',
    domain: 'refund',
    type: TYPES.PERCENT,
    unit: 'percent',
    bounds: { min: 0, max: 100 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: 50,
    clause: '8.2',
    clauseExpectation: null, // clause defines a FEE, not a refund percentage
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Refund percentage inside the late-cancellation window.',
    source: 'server/lib/refunds/policy.js:100',
  },
  {
    key: 'refund.partner_accepted_percent',
    domain: 'refund',
    type: TYPES.PERCENT,
    unit: 'percent',
    bounds: { min: 0, max: 100 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: 50,
    clause: '8.1',
    // A booking a partner has accepted is still inside the free window if the
    // customer gives more than 4 hours' notice — the clause makes no exception.
    clauseExpectation: 100,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Refund percentage once a partner has accepted, regardless of notice.',
    source: 'server/lib/refunds/policy.js:104',
  },
  {
    key: 'refund.auto_approve_ceiling_myr',
    domain: 'refund',
    type: TYPES.MONEY,
    unit: 'myr',
    bounds: { min: 0, max: 10000 },
    scope: SCOPES.GLOBAL,
    audience: [],
    fallback: null, // NO CEILING TODAY — conflict C-03
    clause: '9.2',
    clauseExpectation: 100,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Partial refund above which operations authorisation is required.',
    source: 'server/lib/refunds/policy.js:112',
  },
  {
    key: 'refund.processing_days_min',
    domain: 'refund',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 0, max: 60 },
    scope: SCOPES.GLOBAL,
    audience: ['consumer'],
    fallback: 5,
    clause: '9.4',
    clauseExpectation: 5,
    owner: OWNERS.FINANCE,
    description: 'Lower bound of the stated refund settlement window.',
    source: 'server/lib/chatbot/knowledge.js:44',
  },
  {
    key: 'refund.processing_days_max',
    domain: 'refund',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 0, max: 60 },
    scope: SCOPES.GLOBAL,
    audience: ['consumer'],
    // The chatbot currently states 3–10 working days; the contract says 5–7.
    fallback: 10,
    clause: '9.4',
    clauseExpectation: 7,
    owner: OWNERS.FINANCE,
    description: 'Upper bound of the stated refund settlement window.',
    source: 'server/lib/chatbot/knowledge.js:44',
  },
  {
    key: 'refund.initiation_business_days',
    domain: 'refund',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 0, max: 30 },
    scope: SCOPES.GLOBAL,
    audience: ['consumer'],
    fallback: 3,
    clause: '9.4',
    clauseExpectation: 2,
    owner: OWNERS.FINANCE,
    description: 'Business days within which an approved refund is initiated.',
    source: 'server/lib/chatbot/knowledge.js:44',
  },

  // ── No-show ────────────────────────────────────────────────────────────────
  {
    key: 'noshow.customer_fee_basis',
    domain: 'noshow',
    type: TYPES.ENUM,
    unit: null,
    bounds: { values: ['cancellation_fee', 'fixed', 'percent', 'none'] },
    scope: SCOPES.BOOKING,
    audience: ['consumer', 'partner'],
    fallback: 'none', // NOT IMPLEMENTED — conflict C-13
    clause: '6.15',
    clauseExpectation: 'cancellation_fee',
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'How a customer no-show fee is calculated.',
    source: null,
  },
  {
    key: 'noshow.high_value_percent',
    domain: 'noshow',
    type: TYPES.PERCENT,
    unit: 'percent',
    bounds: { min: 0, max: 100 },
    scope: SCOPES.BOOKING,
    audience: ['consumer', 'partner'],
    fallback: null,
    clause: '6.15',
    clauseExpectation: 50,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Maximum no-show fee percentage on bookings above the high-value threshold.',
    source: null,
  },
  {
    key: 'noshow.partner_late_minutes',
    domain: 'noshow',
    type: TYPES.INTEGER,
    unit: 'minutes',
    bounds: { min: 0, max: 240 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: null,
    clause: '6.13',
    clauseExpectation: 30,
    owner: OWNERS.OPS,
    description: 'Lateness past the arrival window after which the customer may cancel free.',
    source: null,
  },

  // ── Escrow ─────────────────────────────────────────────────────────────────
  {
    key: 'escrow.release_after_confirm_hours',
    domain: 'escrow',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 0, max: 336 },
    scope: SCOPES.BOOKING,
    audience: ['partner'],
    fallback: null, // NO AUTOMATIC RELEASE — conflict C-04
    clause: '7.9',
    clauseExpectation: 24,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Hours after customer confirmation before escrow releases to the partner.',
    source: null,
  },
  {
    key: 'escrow.release_no_response_hours',
    domain: 'escrow',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 0, max: 336 },
    scope: SCOPES.BOOKING,
    audience: ['partner'],
    fallback: null, // NO AUTOMATIC RELEASE — conflict C-04
    clause: '7.9',
    clauseExpectation: 48,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Hours after completion before escrow releases when the customer does not respond.',
    source: null,
  },
  {
    key: 'escrow.freeze_on_dispute',
    domain: 'escrow',
    type: TYPES.BOOLEAN,
    unit: null,
    bounds: null,
    scope: SCOPES.BOOKING,
    audience: ['consumer', 'partner'],
    fallback: true,
    clause: '7.9',
    clauseExpectation: true,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Whether raising a dispute freezes the escrowed amount.',
    source: 'server/routes/escrow.js:46',
  },

  // ── Commission ─────────────────────────────────────────────────────────────
  {
    key: 'commission.rate.default',
    domain: 'commission',
    type: TYPES.RATE,
    unit: 'rate',
    bounds: { min: 0, max: 0.5 },
    scope: SCOPES.ASSIGNMENT,
    audience: ['partner'],
    fallback: 0.20,
    clause: '7.6',
    clauseExpectation: 0.20,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Default platform commission rate.',
    source: 'server/lib/payments/commission.js:25',
  },
  {
    key: 'commission.rate.premium',
    domain: 'commission',
    type: TYPES.RATE,
    unit: 'rate',
    bounds: { min: 0, max: 0.5 },
    scope: SCOPES.ASSIGNMENT,
    audience: ['partner'],
    fallback: 0.18,
    clause: '7.6',
    clauseExpectation: null, // clause permits tiering without fixing the rates
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Commission rate for the premium partner tier.',
    source: 'server/lib/payments/commission.js:26',
  },
  {
    key: 'commission.rate.elite',
    domain: 'commission',
    type: TYPES.RATE,
    unit: 'rate',
    bounds: { min: 0, max: 0.5 },
    scope: SCOPES.ASSIGNMENT,
    audience: ['partner'],
    fallback: 0.15,
    clause: '7.6',
    clauseExpectation: null,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Commission rate for the elite partner tier.',
    source: 'server/lib/payments/commission.js:27',
  },
  {
    key: 'commission.rate.new_partner',
    domain: 'commission',
    type: TYPES.RATE,
    unit: 'rate',
    bounds: { min: 0, max: 0.5 },
    scope: SCOPES.ASSIGNMENT,
    audience: ['partner'],
    fallback: 0.25,
    clause: '7.6',
    clauseExpectation: null,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Commission rate for newly onboarded partners.',
    source: 'server/lib/payments/commission.js:28',
  },
  {
    key: 'commission.snapshot_at_acceptance',
    domain: 'commission',
    type: TYPES.BOOLEAN,
    unit: null,
    bounds: null,
    scope: SCOPES.GLOBAL,
    audience: [],
    fallback: false, // RATE RESOLVED LIVE TODAY — conflict C-05
    clause: '7.6',
    clauseExpectation: true,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Whether the commission rate is frozen when a partner accepts a booking.',
    source: 'server/lib/payments/commission.js:44',
  },
  {
    key: 'commission.change_notice_days',
    domain: 'commission',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 0, max: 90 },
    scope: SCOPES.GLOBAL,
    audience: ['partner'],
    fallback: null,
    clause: '7.6',
    clauseExpectation: 14,
    owner: OWNERS.LEGAL,
    description: 'Notice partners receive before a commission rate change takes effect.',
    source: null,
  },
  {
    key: 'commission.settlement_period',
    domain: 'commission',
    type: TYPES.ENUM,
    unit: null,
    bounds: { values: ['weekly', 'monthly'] },
    scope: SCOPES.GLOBAL,
    audience: ['partner'],
    fallback: 'weekly',
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.FINANCE,
    description: 'How often cash-commission settlements are generated.',
    source: 'server/lib/payouts/schedule.js',
  },

  // ── Payout ─────────────────────────────────────────────────────────────────
  {
    key: 'payout.frequency',
    domain: 'payout',
    type: TYPES.ENUM,
    unit: null,
    bounds: { values: ['daily', 'weekly', 'fortnightly', 'monthly'] },
    scope: SCOPES.GLOBAL,
    audience: ['partner'],
    fallback: 'weekly',
    clause: '7.13',
    clauseExpectation: null,
    owner: OWNERS.FINANCE,
    description: 'How often payout runs are executed.',
    source: 'server/lib/payouts/schedule.js',
  },
  {
    key: 'payout.require_verified_bank',
    domain: 'payout',
    type: TYPES.BOOLEAN,
    unit: null,
    bounds: null,
    scope: SCOPES.GLOBAL,
    audience: ['partner'],
    fallback: true,
    clause: '7.13',
    clauseExpectation: true,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Whether a verified bank account is required to be included in a payout run.',
    source: 'server/routes/payouts.js',
  },
  {
    key: 'payout.settlement_days_max',
    domain: 'payout',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 0, max: 30 },
    scope: SCOPES.GLOBAL,
    audience: ['partner'],
    fallback: 3,
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.FINANCE,
    description: 'Working days within which payout funds should reach a partner bank account.',
    source: 'server/lib/chatbot/knowledge.js:80',
  },

  // ── Liability ──────────────────────────────────────────────────────────────
  {
    key: 'liability.cap_per_booking_myr',
    domain: 'liability',
    type: TYPES.MONEY,
    unit: 'myr',
    bounds: { min: 0, max: 1000000 },
    scope: SCOPES.CLAIM,
    audience: [],
    fallback: null, // NOT ENFORCED — conflict C-06
    clause: '20.7',
    clauseExpectation: 1000,
    owner: OWNERS.LEGAL,
    moneyAffecting: true,
    description: 'Floor of the platform liability cap for a single booking (greater of this or fees retained).',
    source: null,
  },
  {
    key: 'liability.cap_per_12_months_myr',
    domain: 'liability',
    type: TYPES.MONEY,
    unit: 'myr',
    bounds: { min: 0, max: 1000000 },
    scope: SCOPES.CLAIM,
    audience: [],
    fallback: null, // NOT ENFORCED — conflict C-06
    clause: '20.7',
    clauseExpectation: 5000,
    owner: OWNERS.LEGAL,
    moneyAffecting: true,
    description: 'Floor of the platform liability cap per user over any 12-month period.',
    source: null,
  },
  {
    key: 'liability.insurance_referral_threshold_myr',
    domain: 'liability',
    type: TYPES.MONEY,
    unit: 'myr',
    bounds: { min: 0, max: 100000 },
    scope: SCOPES.CLAIM,
    audience: [],
    fallback: 1000,
    clause: '20.10',
    clauseExpectation: null,
    owner: OWNERS.LEGAL,
    moneyAffecting: true,
    description: 'Partner liability above which a claim is routed to their public liability insurer.',
    source: 'server/lib/damageClaims/sla.js:22',
  },
  {
    key: 'liability.max_claim_intake_myr',
    domain: 'liability',
    type: TYPES.MONEY,
    unit: 'myr',
    bounds: { min: 0, max: 1000000 },
    scope: SCOPES.CLAIM,
    audience: [],
    fallback: 50000,
    clause: null, // intake ceiling is operational; the CAP is the contractual limb
    clauseExpectation: null,
    owner: OWNERS.TRUST,
    description: 'Claim amount above which intake is manual rather than self-service.',
    source: 'server/lib/damageClaims/sla.js:25',
  },

  // ── Damage ─────────────────────────────────────────────────────────────────
  {
    key: 'damage.reporting_window_hours',
    domain: 'damage',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 1, max: 720 },
    scope: SCOPES.CLAIM,
    audience: ['consumer', 'partner'],
    fallback: 48,
    clause: '20.10',
    clauseExpectation: 24,
    owner: OWNERS.TRUST,
    description: 'Window after completion within which property damage must be reported.',
    source: 'server/lib/damageClaims/sla.js:19',
  },
  {
    key: 'damage.sla_acknowledge_hours',
    domain: 'damage',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 1, max: 168 },
    scope: SCOPES.CLAIM,
    audience: ['consumer', 'partner'],
    fallback: 24,
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.TRUST,
    description: 'Target to acknowledge a damage claim.',
    source: 'server/lib/damageClaims/sla.js:12',
  },
  {
    key: 'damage.sla_partner_response_hours',
    domain: 'damage',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 1, max: 336 },
    scope: SCOPES.CLAIM,
    audience: ['consumer', 'partner'],
    fallback: 72,
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.TRUST,
    description: 'Time a partner has to respond to a claim.',
    source: 'server/lib/damageClaims/sla.js:13',
  },
  {
    key: 'damage.sla_investigation_hours',
    domain: 'damage',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 1, max: 1440 },
    scope: SCOPES.CLAIM,
    audience: ['consumer', 'partner'],
    fallback: 168,
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.TRUST,
    description: 'Target to complete a damage investigation.',
    source: 'server/lib/damageClaims/sla.js:14',
  },
  {
    key: 'damage.sla_compensation_hours',
    domain: 'damage',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 1, max: 1440 },
    scope: SCOPES.CLAIM,
    audience: ['consumer', 'partner'],
    fallback: 336,
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Target to pay approved compensation, measured from approval.',
    source: 'server/lib/damageClaims/sla.js:15',
  },
  {
    key: 'damage.min_evidence_photos',
    domain: 'damage',
    type: TYPES.INTEGER,
    unit: 'count',
    bounds: { min: 0, max: 20 },
    scope: SCOPES.CLAIM,
    audience: ['consumer'],
    fallback: 1,
    clause: '20.10',
    clauseExpectation: 1,
    owner: OWNERS.TRUST,
    description: 'Photographs required to file a damage claim.',
    source: 'server/routes/damageClaims.js',
  },

  // ── Warranty ───────────────────────────────────────────────────────────────
  {
    key: 'warranty.workmanship_days',
    domain: 'warranty',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 0, max: 365 },
    scope: SCOPES.BOOKING,
    audience: ['consumer', 'partner'],
    fallback: null, // NOT IMPLEMENTED — conflict C-10
    clause: '28.2',
    clauseExpectation: 30,
    owner: OWNERS.OPS,
    description: 'Minimum workmanship guarantee period for repair and installation categories.',
    source: null,
  },
  {
    key: 'warranty.complaint_window_hours.cleaning',
    domain: 'warranty',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 1, max: 8760 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: null, // NOT IMPLEMENTED — conflict C-10
    clause: '28.3',
    clauseExpectation: 48,
    owner: OWNERS.OPS,
    description: 'Quality complaint window for cleaning, beauty, grooming and wellness.',
    source: null,
  },
  {
    key: 'warranty.complaint_window_hours.workmanship',
    domain: 'warranty',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 1, max: 8760 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: null, // NOT IMPLEMENTED — conflict C-10
    clause: '28.3',
    clauseExpectation: 720,
    owner: OWNERS.OPS,
    description: 'Quality complaint window for repair, installation and workmanship categories.',
    source: null,
  },
  {
    key: 'warranty.reperformance_access_days',
    domain: 'warranty',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 1, max: 90 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: null,
    clause: '28.6',
    clauseExpectation: 14,
    owner: OWNERS.OPS,
    description: 'Days within which a customer must give access for a re-performance visit.',
    source: null,
  },

  // ── Payment ────────────────────────────────────────────────────────────────
  {
    key: 'payment.late_interest_monthly_rate',
    domain: 'payment',
    type: TYPES.RATE,
    unit: 'rate',
    bounds: { min: 0, max: 0.2 },
    scope: SCOPES.GLOBAL,
    audience: ['consumer', 'partner'],
    fallback: null, // NOT IMPLEMENTED — conflict C-15
    clause: '7.12',
    clauseExpectation: 0.01,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Monthly interest on amounts not paid when due.',
    source: null,
  },
  {
    key: 'payment.failed_settlement_days',
    domain: 'payment',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 1, max: 90 },
    scope: SCOPES.GLOBAL,
    audience: ['consumer'],
    fallback: null,
    clause: '7.11',
    clauseExpectation: 7,
    owner: OWNERS.FINANCE,
    description: 'Days a customer has to settle a payment that failed after service.',
    source: null,
  },
  {
    key: 'payment.credit_expiry_months',
    domain: 'payment',
    type: TYPES.INTEGER,
    unit: 'months',
    bounds: { min: 1, max: 120 },
    scope: SCOPES.GLOBAL,
    audience: ['consumer'],
    fallback: 12,
    clause: '29.3',
    clauseExpectation: 12,
    owner: OWNERS.FINANCE,
    description: 'Default expiry of promotional credit when no date is stated.',
    source: null,
  },
  {
    key: 'payment.tip_commission_rate',
    domain: 'payment',
    type: TYPES.RATE,
    unit: 'rate',
    bounds: { min: 0, max: 1 },
    scope: SCOPES.GLOBAL,
    audience: ['partner'],
    fallback: null, // TIPPING NOT IMPLEMENTED — conflict C-14
    clause: '10.12',
    clauseExpectation: 0,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Commission taken from a tip. The contract requires zero.',
    source: null,
  },

  // ── Tax ────────────────────────────────────────────────────────────────────
  {
    key: 'tax.sst_service_rate',
    domain: 'tax',
    type: TYPES.RATE,
    unit: 'rate',
    bounds: { min: 0, max: 0.3 },
    scope: SCOPES.BOOKING,
    audience: ['consumer'],
    fallback: 0.08,
    clause: '7.8',
    clauseExpectation: null, // the clause defers to the Service Tax Act, not a figure
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Service tax rate on taxable services.',
    source: 'server/lib/tax/index.js:24 (already DB-backed via TaxConfig)',
  },
  {
    key: 'tax.sst_commission_rate',
    domain: 'tax',
    type: TYPES.RATE,
    unit: 'rate',
    bounds: { min: 0, max: 0.3 },
    scope: SCOPES.ASSIGNMENT,
    audience: ['partner'],
    fallback: 0.08,
    clause: '7.8',
    clauseExpectation: null,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Service tax rate on platform commission.',
    source: 'server/lib/tax/index.js (TaxConfig SST_COMMISSION)',
  },

  // ── Pricing ────────────────────────────────────────────────────────────────
  {
    key: 'pricing.max_surge_multiplier',
    domain: 'pricing',
    type: TYPES.DECIMAL,
    unit: 'multiplier',
    bounds: { min: 1, max: 3 },
    scope: SCOPES.GLOBAL,
    audience: ['consumer'],
    fallback: null, // NO CEILING ENFORCED — conflict C-08
    clause: '10.6',
    clauseExpectation: 1.5,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Maximum surge multiplier applicable to a displayed price.',
    source: 'server/lib/pricing.js:11',
  },

  // ── Partner ────────────────────────────────────────────────────────────────
  {
    key: 'partner.freeze_after_days',
    domain: 'partner',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 1, max: 90 },
    scope: SCOPES.GLOBAL,
    audience: ['partner'],
    fallback: 7,
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.FINANCE,
    description: 'Days a settlement may be overdue before new job offers pause.',
    source: 'server/lib/wallet/freeze.js:25',
  },
  {
    key: 'partner.suspend_payouts_after_days',
    domain: 'partner',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 1, max: 180 },
    scope: SCOPES.GLOBAL,
    audience: ['partner'],
    fallback: 14,
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.FINANCE,
    moneyAffecting: true,
    description: 'Days a settlement may be overdue before payouts are held.',
    source: 'server/lib/wallet/freeze.js:26',
  },
  {
    key: 'partner.reminder_days',
    domain: 'partner',
    type: TYPES.LIST,
    unit: 'days',
    bounds: { itemType: 'integer', min: 0, max: 90 },
    scope: SCOPES.GLOBAL,
    audience: ['partner'],
    fallback: [0, 1, 3, 7],
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.OPS,
    description: 'Overdue-days at which settlement reminders are sent.',
    source: 'server/lib/wallet/freeze.js:24',
  },
  {
    key: 'partner.reverification_months',
    domain: 'partner',
    type: TYPES.INTEGER,
    unit: 'months',
    bounds: { min: 1, max: 60 },
    scope: SCOPES.GLOBAL,
    audience: ['partner'],
    fallback: null,
    clause: '4.3',
    clauseExpectation: 12,
    owner: OWNERS.TRUST,
    description: 'Interval at which partner background screening is repeated.',
    source: null,
  },
  {
    key: 'partner.min_rating',
    domain: 'partner',
    type: TYPES.DECIMAL,
    unit: 'stars',
    bounds: { min: 0, max: 5 },
    scope: SCOPES.GLOBAL,
    audience: ['partner'],
    fallback: null,
    clause: '5.9',
    clauseExpectation: null,
    owner: OWNERS.TRUST,
    description: 'Average rating below which a partner is subject to review.',
    source: null,
  },
  {
    key: 'partner.quality_review_rating',
    domain: 'partner',
    type: TYPES.DECIMAL,
    unit: 'stars',
    bounds: { min: 0, max: 5 },
    scope: SCOPES.GLOBAL,
    audience: [],
    fallback: 3,
    clause: '14.4',
    clauseExpectation: 3,
    owner: OWNERS.TRUST,
    description: 'Rating below which an internal quality review is generated.',
    source: null,
  },
  {
    key: 'partner.appeal_window_days',
    domain: 'partner',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 1, max: 90 },
    scope: SCOPES.GLOBAL,
    audience: ['consumer', 'partner'],
    fallback: null,
    clause: '23.2',
    clauseExpectation: 14,
    owner: OWNERS.LEGAL,
    description: 'Days within which a user may request an internal review of a decision.',
    source: null,
  },

  // ── Support ────────────────────────────────────────────────────────────────
  {
    key: 'support.sla_first_response_hours.urgent',
    domain: 'support',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 1, max: 168 },
    scope: SCOPES.TICKET,
    audience: [],
    fallback: 1,
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.OPS,
    description: 'First-response target for urgent tickets.',
    source: 'server/lib/support/sla.js:8',
  },
  {
    key: 'support.sla_first_response_hours.normal',
    domain: 'support',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 1, max: 168 },
    scope: SCOPES.TICKET,
    audience: [],
    fallback: 12,
    clause: '23.1',
    clauseExpectation: 24, // "aims to acknowledge within twenty-four (24) hours"
    owner: OWNERS.OPS,
    description: 'First-response target for normal-priority tickets.',
    source: 'server/lib/support/sla.js:8',
  },
  {
    key: 'support.sla_resolution_hours.normal',
    domain: 'support',
    type: TYPES.INTEGER,
    unit: 'hours',
    bounds: { min: 1, max: 720 },
    scope: SCOPES.TICKET,
    audience: [],
    fallback: 72,
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.OPS,
    description: 'Resolution target for normal-priority tickets.',
    source: 'server/lib/support/sla.js:8',
  },
  {
    key: 'support.escalation_low_confidence',
    domain: 'support',
    type: TYPES.DECIMAL,
    unit: 'score',
    bounds: { min: 0, max: 1 },
    scope: SCOPES.GLOBAL,
    audience: [],
    fallback: 0.4,
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.OPS,
    description: 'Chatbot retrieval confidence below which a conversation escalates.',
    source: 'server/lib/chatbot/guardrails.js:93',
  },
  {
    key: 'support.escalation_unresolved_turns',
    domain: 'support',
    type: TYPES.INTEGER,
    unit: 'count',
    bounds: { min: 1, max: 10 },
    scope: SCOPES.GLOBAL,
    audience: [],
    fallback: 2,
    clause: null,
    clauseExpectation: null,
    owner: OWNERS.OPS,
    description: 'Low-confidence chatbot turns after which a conversation escalates.',
    source: 'server/lib/chatbot/guardrails.js:94',
  },

  // ── Retention ──────────────────────────────────────────────────────────────
  {
    key: 'retention.financial_records_years',
    domain: 'retention',
    type: TYPES.INTEGER,
    unit: 'years',
    bounds: { min: 1, max: 30 },
    scope: SCOPES.GLOBAL,
    audience: [],
    fallback: null, // NOT IMPLEMENTED — conflict C-11
    clause: '18.11',
    clauseExpectation: 7,
    owner: OWNERS.LEGAL,
    description: 'Retention period for booking and financial records.',
    source: null,
  },
  {
    key: 'retention.chat_logs_days',
    domain: 'retention',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 1, max: 3650 },
    scope: SCOPES.GLOBAL,
    audience: [],
    fallback: null, // NOT IMPLEMENTED — conflict C-11
    clause: '17.4',
    clauseExpectation: 90,
    owner: OWNERS.LEGAL,
    description: 'Minimum retention for chat and masked-call records.',
    source: null,
  },
  {
    key: 'retention.dormancy_months',
    domain: 'retention',
    type: TYPES.INTEGER,
    unit: 'months',
    bounds: { min: 1, max: 120 },
    scope: SCOPES.GLOBAL,
    audience: [],
    fallback: null, // NOT IMPLEMENTED — conflict C-16
    clause: '5.12',
    clauseExpectation: 24,
    owner: OWNERS.LEGAL,
    description: 'Inactivity after which an account may be deactivated.',
    source: null,
  },
  {
    key: 'retention.dormancy_notice_days',
    domain: 'retention',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 1, max: 365 },
    scope: SCOPES.GLOBAL,
    audience: [],
    fallback: null,
    clause: '5.12',
    clauseExpectation: 30,
    owner: OWNERS.LEGAL,
    description: 'Notice given before a dormant account is deactivated.',
    source: null,
  },

  // ── Legal ──────────────────────────────────────────────────────────────────
  {
    key: 'legal.material_change_notice_days',
    domain: 'legal',
    type: TYPES.INTEGER,
    unit: 'days',
    bounds: { min: 0, max: 90 },
    scope: SCOPES.GLOBAL,
    audience: ['consumer', 'partner'],
    fallback: null,
    clause: '25.2',
    clauseExpectation: 14,
    owner: OWNERS.LEGAL,
    description: 'Notice before a material change to the Terms takes effect.',
    source: null,
  },
  {
    key: 'legal.bind_booking_to_terms_version',
    domain: 'legal',
    type: TYPES.BOOLEAN,
    unit: null,
    bounds: null,
    scope: SCOPES.BOOKING,
    audience: [],
    fallback: false, // NOT IMPLEMENTED — conflict C-09
    clause: '25.5',
    clauseExpectation: true,
    owner: OWNERS.LEGAL,
    description: 'Whether a booking records the Terms version in force at confirmation.',
    source: null,
  },
];

/** Fast lookup by key. */
export const KEYS_BY_ID = new Map(POLICY_KEYS.map((k) => [k.key, k]));

/** Every declared key id. */
export const ALL_KEYS = POLICY_KEYS.map((k) => k.key);

/** Definition for a key, or null. Never throws — callers decide how to degrade. */
export const getKeyDef = (key) => KEYS_BY_ID.get(key) || null;

/** Keys in a domain. */
export const keysInDomain = (domain) => POLICY_KEYS.filter((k) => k.domain === domain);

/** Keys frozen at a given snapshot boundary. */
export const keysInScope = (scope) => POLICY_KEYS.filter((k) => k.scope === scope);

/**
 * Keys an audience may read through the public bundle.
 * A consumer bundle must never contain commission rates — audience filtering is
 * server-side for exactly that reason.
 */
export const keysForAudience = (audience) => POLICY_KEYS.filter((k) => (k.audience || []).includes(audience));

/** Keys that require two approvers. */
export const moneyAffectingKeys = () => POLICY_KEYS.filter((k) => k.moneyAffecting === true);

/**
 * The fallback map — what the code uses when the Registry is unseeded or
 * unreachable. Seeded as v1 so adopting the Registry changes no behaviour.
 * A null fallback means "not implemented today", which is itself a conflict when
 * the governing clause states a value.
 */
export const fallbacks = () => Object.fromEntries(POLICY_KEYS.map((k) => [k.key, k.fallback]));
