// AUTO-GENERATED — slug → bundled image asset. Regenerate by re-running the
// generator in the chat that created it (scans assets/img/{categories,services}).
import type { ImageSourcePropType } from 'react-native';

export const CATEGORY_IMAGES: Record<string, ImageSourcePropType> = {
  'ac-services': require('../../assets/img/categories/ac-services.webp'),
  'appliance-repair': require('../../assets/img/categories/appliance-repair.webp'),
  'beauty-wellness-women': require('../../assets/img/categories/beauty-wellness-women.webp'),
  'carpenter': require('../../assets/img/categories/carpenter.webp'),
  'cleaning': require('../../assets/img/categories/cleaning.webp'),
  'electrician': require('../../assets/img/categories/electrician.webp'),
  'handyman-installation': require('../../assets/img/categories/handyman-installation.webp'),
  'instant-help': require('../../assets/img/categories/instant-help.webp'),
  'mens-grooming-massage': require('../../assets/img/categories/mens-grooming-massage.webp'),
  'painting-renovation': require('../../assets/img/categories/painting-renovation.webp'),
  'pest-control': require('../../assets/img/categories/pest-control.webp'),
  'plumbing': require('../../assets/img/categories/plumbing.webp'),
};

export const SERVICE_IMAGES: Record<string, ImageSourcePropType> = {
  'ac-chemical-cleaning': require('../../assets/img/services/ac-chemical-cleaning.webp'),
  'ac-cooling-repair': require('../../assets/img/services/ac-cooling-repair.webp'),
  'ac-gas-refill': require('../../assets/img/services/ac-gas-refill.webp'),
  'ac-installation': require('../../assets/img/services/ac-installation.webp'),
  'ac-servicing': require('../../assets/img/services/ac-servicing.webp'),
  'ac-water-leakage': require('../../assets/img/services/ac-water-leakage.webp'),
  'ant-control': require('../../assets/img/services/ant-control.webp'),
  'beard-styling': require('../../assets/img/services/beard-styling.webp'),
  'bed-bug-treatment': require('../../assets/img/services/bed-bug-treatment.webp'),
  'blocked-drain-cleaning': require('../../assets/img/services/blocked-drain-cleaning.webp'),
  'body-massage-women': require('../../assets/img/services/body-massage-women.webp'),
  'bridal-makeup-hairdo': require('../../assets/img/services/bridal-makeup-hairdo.webp'),
  'chimney-hood-cleaning': require('../../assets/img/services/chimney-hood-cleaning.webp'),
  'cockroach-control': require('../../assets/img/services/cockroach-control.webp'),
  'curtain-rod-installation': require('../../assets/img/services/curtain-rod-installation.webp'),
  'deep-cleaning': require('../../assets/img/services/deep-cleaning.webp'),
  'deep-sanitisation-bathroom': require('../../assets/img/services/deep-sanitisation-bathroom.webp'),
  'deep-tissue-massage': require('../../assets/img/services/deep-tissue-massage.webp'),
  'door-repair': require('../../assets/img/services/door-repair.webp'),
  'emergency-callout': require('../../assets/img/services/emergency-callout.webp'),
  'exterior-painting': require('../../assets/img/services/exterior-painting.webp'),
  'face-threading-full-face': require('../../assets/img/services/face-threading-full-face.webp'),
  'facial-standard': require('../../assets/img/services/facial-standard.webp'),
  'fan-installation': require('../../assets/img/services/fan-installation.webp'),
  'flush-cistern-repair': require('../../assets/img/services/flush-cistern-repair.webp'),
  'full-house-cleaning': require('../../assets/img/services/full-house-cleaning.webp'),
  'furniture-assembly': require('../../assets/img/services/furniture-assembly.webp'),
  'gel-nails': require('../../assets/img/services/gel-nails.webp'),
  'geyser-repair': require('../../assets/img/services/geyser-repair.webp'),
  'hair-botox': require('../../assets/img/services/hair-botox.webp'),
  'hair-colouring': require('../../assets/img/services/hair-colouring.webp'),
  'hair-smoothening-rebonding': require('../../assets/img/services/hair-smoothening-rebonding.webp'),
  'hair-spa-treatment': require('../../assets/img/services/hair-spa-treatment.webp'),
  'hydrafacial': require('../../assets/img/services/hydrafacial.webp'),
  'ikea-furniture-assembly': require('../../assets/img/services/ikea-furniture-assembly.webp'),
  'instant-hourly-handyman': require('../../assets/img/services/instant-hourly-handyman.webp'),
  'interior-painting': require('../../assets/img/services/interior-painting.webp'),
  'keratin-treatment': require('../../assets/img/services/keratin-treatment.webp'),
  'leakage-repair': require('../../assets/img/services/leakage-repair.webp'),
  'light-installation': require('../../assets/img/services/light-installation.webp'),
  'lock-replacement': require('../../assets/img/services/lock-replacement.webp'),
  'mattress-cleaning': require('../../assets/img/services/mattress-cleaning.webp'),
  'mcb-db-repair': require('../../assets/img/services/mcb-db-repair.webp'),
  'mens-facial': require('../../assets/img/services/mens-facial.webp'),
  'mens-hair-colour': require('../../assets/img/services/mens-hair-colour.webp'),
  'mens-haircut': require('../../assets/img/services/mens-haircut.webp'),
  'microwave-repair': require('../../assets/img/services/microwave-repair.webp'),
  'mirror-installation': require('../../assets/img/services/mirror-installation.webp'),
  'mosquito-fogging': require('../../assets/img/services/mosquito-fogging.webp'),
  'move-in-out-cleaning': require('../../assets/img/services/move-in-out-cleaning.webp'),
  'pipe-replacement': require('../../assets/img/services/pipe-replacement.webp'),
  'refrigerator-repair': require('../../assets/img/services/refrigerator-repair.webp'),
  'rica-waxing-full-leg': require('../../assets/img/services/rica-waxing-full-leg.webp'),
  'ro-system-repair': require('../../assets/img/services/ro-system-repair.webp'),
  'rodent-control': require('../../assets/img/services/rodent-control.webp'),
  'shelf-installation': require('../../assets/img/services/shelf-installation.webp'),
  'smart-lock-installation': require('../../assets/img/services/smart-lock-installation.webp'),
  'sofa-cleaning': require('../../assets/img/services/sofa-cleaning.webp'),
  'swedish-massage-men': require('../../assets/img/services/swedish-massage-men.webp'),
  'switch-outlet-replacement': require('../../assets/img/services/switch-outlet-replacement.webp'),
  'tap-repair-replacement': require('../../assets/img/services/tap-repair-replacement.webp'),
  'termite-treatment': require('../../assets/img/services/termite-treatment.webp'),
  'terrace-waterproofing': require('../../assets/img/services/terrace-waterproofing.webp'),
  'tv-mounting': require('../../assets/img/services/tv-mounting.webp'),
  'tv-repair': require('../../assets/img/services/tv-repair.webp'),
  'wall-panels-installation': require('../../assets/img/services/wall-panels-installation.webp'),
  'wallpaper-installation': require('../../assets/img/services/wallpaper-installation.webp'),
  'wash-basin-installation': require('../../assets/img/services/wash-basin-installation.webp'),
  'washing-machine-repair': require('../../assets/img/services/washing-machine-repair.webp'),
  'wiring-work': require('../../assets/img/services/wiring-work.webp'),
  'womens-haircut-styling': require('../../assets/img/services/womens-haircut-styling.webp'),
};

export const HERO_IMAGE = require('../../assets/img/hero.png') as ImageSourcePropType;
export const LOGO_IMAGE = require('../../assets/img/logo.png') as ImageSourcePropType;

export const categoryImage = (slug?: string): ImageSourcePropType | undefined =>
  slug ? CATEGORY_IMAGES[slug] : undefined;
export const serviceImage = (slug?: string): ImageSourcePropType | undefined =>
  slug ? SERVICE_IMAGES[slug] : undefined;
