-- Reconcile migration history with prisma/schema.prisma.
--
-- ADDITIVE AND NON-DESTRUCTIVE. Five nullable-or-defaulted columns, one
-- constraint relaxation and one unique index. Nothing is renamed, dropped or
-- rewritten, and no row is modified.
--
-- WHY THIS EXISTS. Two feature commits added fields to the User model without
-- generating a migration — 1f2c3b6 (consumer OTP auth, onboarding and profile)
-- and 47a6cfd (Firebase phone/Google auth). The development database received
-- them through `prisma db push`, which writes no migration file, so the schema
-- and the migration history silently diverged. A database built by
-- `prisma migrate deploy` alone was missing all five columns: the first query
-- against User failed with P2022 (`profileComplete` does not exist), which made
-- `node prisma/seed.js` — and therefore any fresh staging deploy — impossible.
--
-- This is the forward-only reconciliation, generated by
--   prisma migrate diff --from-migrations prisma/migrations
--                       --to-schema-datamodel prisma/schema.prisma
-- so it is exactly the delta Prisma itself computes, no more and no less.
--
-- SCOPE. User and Notification only. No financial table (EscrowLedger,
-- WalletLedgerEntry, PayoutRecord, CommissionSettlement, Payment,
-- RefundRequest, PartnerWallet) is referenced, and no application behaviour
-- changes — the application already assumes this shape, which is why the
-- development database works and a migrated one did not.
--
-- Notification."updatedAt" carried a DEFAULT that the schema's `@updatedAt`
-- does not declare. Prisma writes that column on every update, so dropping the
-- default changes nothing at runtime; it only stops migrate from reporting
-- perpetual drift.
--
-- EMPTY-DATABASE SAFE. `profileComplete` and `tokenVersion` are NOT NULL with
-- defaults, so they backfill deterministically on any existing row. Making
-- `email` nullable widens the column and cannot fail. `User_firebaseUid_key` is
-- unique over a fresh, all-NULL column, and Postgres does not treat NULLs as
-- equal, so the index is valid however many rows already exist.

-- AlterTable
ALTER TABLE "Notification" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "addresses" JSONB,
ADD COLUMN     "consumerProfile" JSONB,
ADD COLUMN     "firebaseUid" TEXT,
ADD COLUMN     "profileComplete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "tokenVersion" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "email" DROP NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "User_firebaseUid_key" ON "User"("firebaseUid");
